### ISSUE TITLE
Document infrastructure and deployment logic

### ISSUE THREAD

**Issue by klausenbusk** [cdnjs/static-website#11]
Hi

Looking at the code, I can't figure out where this is hosted and how new versions is deployed. I think CDNJS should be as transparent as possible, and documenting the infrastructure and deployment logic is part of that.

**Comment by MattIPv4** [comment]
This site isn't currently in production nor is it really considered an active stack, still very much in the development stages. Once I start looking at moving this to being the production site deployment steps will be documented similar to cdnjs/api-server.
