### ISSUE TITLE
Race condition in suggest on the main page

### ISSUE THREAD

**Issue by alexey-milovidov** [cdnjs/static-website#110]
## Information
https://whatismybrowser.com/w/LG56TPW

### Description
When I quickly type library name in the main text form, the input is garbled.

### Steps to reproduce
Open https://cdnjs.com/ and quickly type some library name like `marked`.
If the problem does not reproduce, add random latencies in the network communication.
Refresh the page and try again. Ensure you type the text quickly enough but don't copy-pasted it.

### Expected behavior
No issue exists

**Comment by mtrunt** [comment]
I can take a look at this if it's still available.

**Comment by MattIPv4** [comment]
Yes, I believe this still needs investigating/fixing -- it seems reproducible if network throttling is applied via developer tools.
