### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [cdnjs/static-website#16]
## Remove Google Analytics

Hello! I regularly use CDNJS, so I felt like this is an issue I really should speak on.

I'm quite confused as to why this brilliant resource uses [Google Analytics, which tracks people across the internet, becoming the subject of million-dollar lawsuits](https://www.reuters.com/article/us-alphabet-google-privacy-lawsuit-idUSKBN23933H). I'm quite worried that we are setting a bad example here.

Personally, I think we, as a community, should research alternatives to Google Analytics.

Thanks! :D

**Comment by MattIPv4** [comment]
The plan is to continue using GA, it's industry standard and what we've used for a long time. If you don't like it, you are welcome to use a browser extension to block it -- we do nothing funky to force it.
