### ISSUE TITLE
Add Tyler to team list

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/static-website#24]
### Feature description

@tc80 is now a core contributor to cdnjs, they should be added to the team list on /about.

@tc80, could you share the following info for the site:

- Image to use (profile, avatar, etc.)
- Name to display
- Twitter (if applicable)

### How the feature is useful

Informational.

**Comment by tc80** [comment]
aw thanks @MattIPv4 , sorry I just saw this now!

You can use my full name -- Tyler Caslin
Pic is below (also updated my github with it): 
![pic](https://user-images.githubusercontent.com/34184511/88351126-50b7e580-cd23-11ea-83f9-c08a0686547b.JPG)
