### ISSUE TITLE
There is an Issue with user interface.

### ISSUE THREAD

**Issue by AbdullahMateen** [cdnjs/static-website#30]
## Information
https://www.whatismybrowser.com/w/DMTLL9Y
this link show that i have JavaScript enabled: No

as a proof
http://www.bom.gov.au/australia/radar/about/clickme.shtml
![Screenshot(3)](https://user-images.githubusercontent.com/22071476/89379115-a1a9df80-d70e-11ea-97c1-8806782e4643.png)

## Details
There is an Issue with user interface.

### Description
I searched for bootstrap 5 alpha and the list on "https://cdnjs.com/libraries/twitter-bootstrap/5.0.0-alpha1" page was not showing correct list.

### Steps to reproduce
1) go to **https://cdnjs.com/**
2) search for "**bootstrap**" in search bar
3) select first option in results named "**twitter-bootstrap @ 4.5.1"**
4) select version "**5.0.0-alpha 1**" from version dropdown that go to "https://cdnjs.com/libraries/twitter-bootstrap/5.0.0-alpha1" link
5) then on that page click on "**5.0.0-alpha1**" from breadcrumb 'Home / Libraries / twitter-bootstrap / **5.0.0-alpha1**'
6) after clicking when the page showed up the list on that page was not showing correctly.

this issue appear on all pages when u click on version from breadcrumb 

### Expected behavior
what i think the cdnJs link list should be displayed like this page "https://cdnjs.com/libraries/twitter-bootstrap"

### Screenshots

Error page screenshot

![Screenshot (1)_LI](https://user-images.githubusercontent.com/22071476/89378868-29431e80-d70e-11ea-870b-5a4af5ce83de.jpg)

Expected result screenshot

![Screenshot(4)](https://user-images.githubusercontent.com/22071476/89379012-6f987d80-d70e-11ea-815e-d89c171bc8f2.png)

**Comment by MattIPv4** [comment]
Can reproduce on the production site, as well as in development. Will investigate!

**Comment by MattIPv4** [comment]
Fixed on staging (https://staging.heroku.cdnjs.dev/libraries/twitter-bootstrap/5.0.0-alpha1) with https://github.com/cdnjs/static-website/commit/7d97cd5556d44b03f2131c1b71d939a673b1ea6a -- will deploy to prod.

**Comment by MattIPv4** [comment]
Fixed in production :) Thanks for the report.
