### ISSUE TITLE
DuckDuckGo !cdnjs search not working

### ISSUE THREAD

**Issue by TalooBob** [cdnjs/static-website#34]
I love the new look of the website, although i dont like how when i search in duckduckgo `!cdnjs ____` that it just takes me to the homepage, whereas before it would actually search my query on cdnjs
thank you.

**Comment by MattIPv4** [comment]
Hm, that sounds odd. I'm not sure what the internals are for how DuckDuckGo is searching cdnjs, but we publish the correct metadata for search forms. If this persists past the final rollout of the new site I'll investigate further.

**Comment by TalooBob** [comment]
Hi, I clicked the link that said go back to the classic website, and now the link that says go back to the beta website doesn't work anymore.
thanks.
________________________________

**Comment by MattIPv4** [comment]
After clicking on the link to go back to the beta site, you may then need to refresh the page manually.

**Comment by TalooBob** [comment]
thanks,
I have just tried that and it just stayed on the classic website,
thanks for your help.
________________________________

**Comment by MattIPv4** [comment]
I cannot reproduce this behaviour, are you blocking cookies? Accessing the beta site requires a cookie named `b` being set to equal `1`.
