### ISSUE TITLE
SSL error on cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by mbardelmeijer** [cdnjs/static-website#37]
# Information
https://whatismybrowser.com/w/3HMWJ2G

### Description
When navigating to https://cdnjs.cloudflare.com/, it shows an SSL error. Previously it was redirected to cdnjs.com.

### Steps to reproduce
1. Go to https://cdnjs.cloudflare.com/ in your browser
2. See the ERR_SSL_VERSION_OR_CIPHER_MISMATCH error

### Expected behavior
301 redirect to cdnjs.com

### Screenshots

![image](https://user-images.githubusercontent.com/1583095/90007645-6887e700-dc9b-11ea-9e9e-30e743d8888c.png)

**Comment by MattIPv4** [comment]
Hi there,

Thanks for the report. Our teams are aware of the issue and are working to resolve it as fast as they can.

You can track the incident here: https://status.cdnjs.com/incidents/yv1ptjhnp6ky

\- Matt.

**Comment by mbardelmeijer** [comment]
Nevermind just saw the status page update 🙈 

Ref: https://www.cloudflarestatus.com/incidents/vtlmfzqmc8h7
