### ISSUE TITLE
Search box autofocus

### ISSUE THREAD

**Issue by andersmmg** [cdnjs/static-website#41]
### Feature description
The search box should be focused automatically when you open the homepage

### How the feature is useful
On the old version (if I remember correctly), I always open it up and start typing a query right away, it makes it way faster to do a search

**Comment by MattIPv4** [comment]
This was actually already resolved in https://github.com/cdnjs/static-website/commit/488427f085b1ec0fae88f074ae3f6cafbf060e0c -- looks like I never pushed this to production though, will do now.

**Comment by MattIPv4** [comment]
This is now live in production.
