### ISSUE TITLE
Bad SEO

### ISSUE THREAD

**Issue by tomas-wrobel** [cdnjs/static-website#45]
Hello,

The problem is SEO. There is missing description in Google but in Bing there is. When I browse your code I see:
``` html
<meta data-n-head="ssr" data-hid="description" name="description" content="Simple. Fast. Reliable. Content delivery at its finest. cdnjs is a free and open-source CDN service trusted by over 10% of websites, powered by Cloudflare. We make it faster and easier to load library files on your websites.">
```
So I don’t know where is the problem.

**Comment by MattIPv4** [comment]
Google is showing a description for me, but I'll request a re-index :)
![image](https://user-images.githubusercontent.com/12371363/92772306-824c4500-f393-11ea-964b-e86401b68621.png)
