### ISSUE TITLE
Canonical URL always points to index

### ISSUE THREAD

**Issue by manniL** [cdnjs/static-website#46]
Hey 👋🏻

I've noticed that your canonical URL setup might be flawed:

First, the `canonicalURL`meta tag doesn't exist (so it can be removed).
https://github.com/cdnjs/static-website/blob/488427f085b1ec0fae88f074ae3f6cafbf060e0c/nuxt.config.js#L52

Second (and more important), the canonical URL *always points to the root page* while you usually want a self-referencing canonical link per page.

https://github.com/cdnjs/static-website/blob/488427f085b1ec0fae88f074ae3f6cafbf060e0c/nuxt.config.js#L72

**Comment by MattIPv4** [comment]
Nice catch, will address this now :)
