### ISSUE TITLE
Improve site responsiveness on tablet/mobile

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/static-website#57]
### Feature description

The site works great but isn't overly responsive. We should improve the responsiveness of the site so that it works well on mobile devices as well as tablet devices and different desktop sizes.

### How the feature is useful

Allows more folks to easily access and use the site.

**Comment by souvik362** [comment]
Hey @MattIPv4 ,
### added this style changes what you think about this 
![Screenshot 2020-10-06 173840](https://user-images.githubusercontent.com/58888934/95200349-dbc15b80-07fb-11eb-8228-fecde09be3c0.png)
Is it looks good and follow your brand guidelines Let me Know

**Comment by MattIPv4** [comment]
Looks like you've just inverted the site -- Not really looking for color changes like this, this issue about making the site have a responsive layout across different screen sizes.

**Comment by souvik362** [comment]
I did it just for fun😀
Not even changes any code

**Comment by rsales** [comment]
Hi @MattIPv4, I would love to be able to work on the development of this responsive implementation.

I will be very happy if I can contribute to the project.


## Actual page version mobile.
<img width="397" alt="Screen Shot 2020-10-08 at 22 35 07" src="https://user-images.githubusercontent.com/4354492/95531302-98f7b300-09b6-11eb-83d4-3f37df745715.png">

**Comment by MattIPv4** [comment]
@rsales Looks great! PR whenever :)
