### ISSUE TITLE
Update 'Request Package' Links on Search Page

### ISSUE THREAD

**Issue by s-crypt** [cdnjs/static-website#82]
At [/blob/master/components/search/primary_search.vue](https://github.com/cdnjs/static-website/blob/master/components/search/primary_search.vue) and therefore when searching, the links at the bottom point to this repository instead of `cdnjs/packages` for suggesting new packages and searching for package requests.

**Comment by s-crypt** [comment]
Hmm. Even though the PR was merged, the website does not seem to be updated. 
@MattIPv4 would you know of any reason that this could be the case?

**Comment by MattIPv4** [comment]
Yes -- because I haven't yet deployed it to production: https://github.com/cdnjs/static-website/tree/production

**Comment by MattIPv4** [comment]
This has since been deployed to prod.
